on:
  push:
    tags:
      - '*'

jobs:
  build-spk:
    name: Build Package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        dsm: ["7.0"]
        arch: ["geminilake"]
        projects: ["./ghr"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Package with local action
        uses: ./
        with:
          dsm: ${{ matrix.dsm }}
          arch: ${{ matrix.arch }}
          projects: ${{ matrix.projects }}
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
            name: packages
            path: ./bin/*.spk

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-spk
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/*.spk
          draft: false
          prerelease: false
